foodtrackingcodefirst/foodtrackingcodefirst/Models/Nutrition.cs
using System.ComponentModel.DataAnnotations;

namespace foodtrackingcodefirst.Models
{
    public class Nutrition
    {
        [Key]
        public int NutritionID { get; set; }
        public string NutritionType { get; set; }
        public string Vitamins { get; set; }
        public string Minerals { get; set; }

        public bool PhisicalActivity { get; set; }

        public string BloodValue { get; set; }


    }
}

foodtrackingcodefirst/foodtrackingcodefirst/Controllers/NutritionController.cs
using foodtrackingcodefirst.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace foodtrackingcodefirst.Controllers
{
    public class NutritionController : Controller
    {
        public readonly ApplicationDbContext dbContext;
        public NutritionController(ApplicationDbContext dbcontext)
        {
            this.dbContext = dbcontext;
        }
        public IActionResult Index(string x)
        {
            var result = from a in dbContext.nutritions
                         select a;

            if (x != null)
            {
                result = result.Where(i => i.NutritionType.Contains(x));
            }
            return View(result);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Nutrition nutrition)
        {
            dbContext.Add(nutrition);
            dbContext.SaveChanges();
            return RedirectToAction("Index");

        }
        public IActionResult Edit(int id)
        {
            var update = dbContext.nutritions.Find(id);
            return View(update);
        }

        [HttpPost]
        public IActionResult Edit(int id, Nutrition nutrition)
        {
            dbContext.Update(nutrition);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var delete = dbContext.nutritions.Find(id);
            return View(delete);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult Sil(int id)
        {
            var delete = dbContext.nutritions.Find(id);
            dbContext.nutritions.Remove(delete);
            dbContext.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

foodtrackingcodefirst/foodtrackingcodefirst/Views/Nutrition/Create.cshtml
@model foodtrackingcodefirst.Models.Nutrition

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Nutrition</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NutritionType" class="control-label"></label>
                <input asp-for="NutritionType" class="form-control" />
                <span asp-validation-for="NutritionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vitamins" class="control-label"></label>
                <input asp-for="Vitamins" class="form-control" />
                <span asp-validation-for="Vitamins" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Minerals" class="control-label"></label>
                <input asp-for="Minerals" class="form-control" />
                <span asp-validation-for="Minerals" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PhisicalActivity" /> @Html.DisplayNameFor(model => model.PhisicalActivity)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="BloodValue" class="control-label"></label>
                <input asp-for="BloodValue" class="form-control" />
                <span asp-validation-for="BloodValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

foodtrackingcodefirst/foodtrackingcodefirst/Views/Nutrition/Delete.cshtml
@model foodtrackingcodefirst.Models.Nutrition

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Nutrition</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NutritionType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NutritionType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vitamins)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vitamins)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Minerals)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Minerals)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhisicalActivity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhisicalActivity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BloodValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BloodValue)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NutritionID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

foodtrackingcodefirst/foodtrackingcodefirst/Views/Nutrition/Edit.cshtml
@model foodtrackingcodefirst.Models.Nutrition

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Nutrition</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NutritionID" />
            <div class="form-group">
                <label asp-for="NutritionType" class="control-label"></label>
                <input asp-for="NutritionType" class="form-control" />
                <span asp-validation-for="NutritionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vitamins" class="control-label"></label>
                <input asp-for="Vitamins" class="form-control" />
                <span asp-validation-for="Vitamins" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Minerals" class="control-label"></label>
                <input asp-for="Minerals" class="form-control" />
                <span asp-validation-for="Minerals" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PhisicalActivity" /> @Html.DisplayNameFor(model => model.PhisicalActivity)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="BloodValue" class="control-label"></label>
                <input asp-for="BloodValue" class="form-control" />
                <span asp-validation-for="BloodValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

foodtrackingcodefirst/foodtrackingcodefirst/Views/Nutrition/Index.cshtml
@model IEnumerable<foodtrackingcodefirst.Models.Nutrition>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nutrition List</h1>
<br />
<br />
@using (Html.BeginForm("Index", "Nutrition"))
{
    @Html.TextBox("x","",new{style="width:400px; margin-left:500px;", placeholder="Please Enter Nutrition Type..."})
    <input type="Submit" value="Search" style="color:blue; margin-top:5px; margin-left:500px; width:400px;" />
}
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NutritionType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vitamins)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Minerals)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhisicalActivity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BloodValue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NutritionType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vitamins)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Minerals)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhisicalActivity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BloodValue)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.NutritionID">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.NutritionID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>